### ISSUE TITLE
Passing user data from index.html to main.html

### ISSUE THREAD

**Issue by Brian-Kaplan** [Brian-Kaplan/Collaborative-Music-Player#15]
Any of you guys understand how to pass data from one page to another? 

For example.

When a user is logged in firebase returns a bunch of information to the page that is relevant to the user. mostly just the uid is important so we can get all the information about a user. When we are redirected to main.html how do we pass that uid data so it can be used to retrieve user information when needed.

**Comment by mluke94** [comment]
We can look into it on Sunday. I am currently working on combining everyone's work from the last week properly.

**Comment by Brian-Kaplan** [comment]
Fixed by using cookies
